-- Generado por scripts/export-supabase-seed.mts · NO editar a mano.
-- Fuente: app/teacher-catalog.ts
-- 23 docentes · 102 asignaciones

insert into teachers (code, full_name, initials) values
  ('brenda-elicet-giles-miranda', 'Brenda Elicet Giles Miranda', 'BE'),
  ('veronica-pamela-jimenez-gutierrez', 'Verónica Pamela Jiménez Gutiérrez', 'VP'),
  ('elias-marcelo-tejeda-aguirre', 'Elias Marcelo Tejeda Aguirre', 'EM'),
  ('maria-fernanda-rojas-pena', 'Maria Fernanda Rojas Peña', 'MF'),
  ('jesus-ernesto-ramos-torres', 'Jesus Ernesto Ramos Torres', 'JE'),
  ('cecilia-guadalupe-castillo-ortiz', 'Cecilia Guadalupe Castillo Ortiz', 'CG'),
  ('sheccid-tirado-cuellar', 'Sheccid Tirado Cuellar', 'ST'),
  ('julio-adrian-cerna-estrada', 'Julio Adrian Cerna Estrada', 'JA'),
  ('jesus-fabian-arellano-ornelas', 'Jesus Fabian Arellano Ornelas', 'JF'),
  ('emilia-elizabeth-sanchez-arellano', 'Emilia Elizabeth Sanchez Arellano', 'EE'),
  ('melissa-arleth-balverde-juarez', 'Melissa Arleth Balverde Juarez', 'MA'),
  ('jessica-maria-orrante-alcaraz', 'Jessica Maria Orrante Alcaraz', 'JM'),
  ('eli-andres-lopez-gonzalez', 'Eli Andres Lopez Gonzalez', 'EA'),
  ('jahayra-elizabeth-lopez-flores', 'Jahayra Elizabeth Lopez Flores', 'JE'),
  ('santiago-garate-martinez', 'Santiago Garate Martinez', 'SG'),
  ('perla-guadalupe-morales-partida', 'Perla Guadalupe Morales Partida', 'PG'),
  ('karime-sinahi-pena-huerta', 'Karime Sinahí Peña Huerta', 'KS'),
  ('teresita-de-jesus-ruiz-castaneda', 'Teresita De Jesús Ruiz Castañeda', 'TD'),
  ('norma-carolina-lizarraga-osuna', 'Norma Carolina Lizarraga Osuna', 'NC'),
  ('elizabeth-gaxiola-tirado', 'Elizabeth Gaxiola Tirado', 'EG'),
  ('beatriz-gutierrez-duran', 'Beatriz Gutierrez Duran', 'BG'),
  ('marielisa-osuna-ramirez', 'Marielisa Osuna Ramirez', 'MO'),
  ('ana-isabel-laris-cutino', 'Ana Isabel Laris Cutiño', 'AI')
on conflict (code) do update set full_name = excluded.full_name, initials = excluded.initials;

insert into teaching_assignments (teacher_id, cycle_id, subject, school_level, grade, group_name)
select t.id, '2026-2027', v.subject, v.school_level, v.grade, v.group_name
from (values
  ('brenda-elicet-giles-miranda', 'Ciencias Naturales, Experimentales Y Tecnología I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('veronica-pamela-jimenez-gutierrez', 'Ciencias Sociales I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('elias-marcelo-tejeda-aguirre', 'Cultura Digital I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('maria-fernanda-rojas-pena', 'Danza', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('jesus-ernesto-ramos-torres', 'Deportes', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('sheccid-tirado-cuellar', 'Inglés I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('veronica-pamela-jimenez-gutierrez', 'Laboratorio De Investigación', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('julio-adrian-cerna-estrada', 'Lengua Y Comunicación I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('jesus-fabian-arellano-ornelas', 'Música', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('emilia-elizabeth-sanchez-arellano', 'Pensamiento Filosófico Y Humanidades I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('elias-marcelo-tejeda-aguirre', 'Pensamiento Matemático I', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('melissa-arleth-balverde-juarez', 'Socioemocional', 'Preparatoria', '1.º de preparatoria', 'Grupo A'),
  ('jessica-maria-orrante-alcaraz', 'Ciencias (biología)', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('eli-andres-lopez-gonzalez', 'Geografía', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('emilia-elizabeth-sanchez-arellano', 'Historia', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('julio-adrian-cerna-estrada', 'Lengua Materna (español)', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('jahayra-elizabeth-lopez-flores', 'Matemáticas', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('jesus-fabian-arellano-ornelas', 'Taller De Artes', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '1.º de secundaria', 'Grupo A'),
  ('jessica-maria-orrante-alcaraz', 'Ciencias (biología)', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('eli-andres-lopez-gonzalez', 'Geografía', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('emilia-elizabeth-sanchez-arellano', 'Historia', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('julio-adrian-cerna-estrada', 'Lengua Materna (español)', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('jahayra-elizabeth-lopez-flores', 'Matemáticas', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('jesus-fabian-arellano-ornelas', 'Taller De Artes', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '1.º de secundaria', 'Grupo B'),
  ('karime-sinahi-pena-huerta', 'Ciencias (física)', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('emilia-elizabeth-sanchez-arellano', 'Historia Ii', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('teresita-de-jesus-ruiz-castaneda', 'Lengua Materna (español)', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('jahayra-elizabeth-lopez-flores', 'Matemáticas', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('maria-fernanda-rojas-pena', 'Taller De Artes', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '2.º de secundaria', 'Grupo A'),
  ('karime-sinahi-pena-huerta', 'Ciencias (física)', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('emilia-elizabeth-sanchez-arellano', 'Historia Ii', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('teresita-de-jesus-ruiz-castaneda', 'Lengua Materna (español)', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('karime-sinahi-pena-huerta', 'Matemáticas', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('maria-fernanda-rojas-pena', 'Taller De Artes', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '2.º de secundaria', 'Grupo B'),
  ('maria-fernanda-rojas-pena', 'Artes', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('karime-sinahi-pena-huerta', 'Ciencias (física)', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('emilia-elizabeth-sanchez-arellano', 'Historia Ii', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('teresita-de-jesus-ruiz-castaneda', 'Lengua Materna (español)', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('jahayra-elizabeth-lopez-flores', 'Matemáticas', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '2.º de secundaria', 'Grupo C'),
  ('jesus-fabian-arellano-ornelas', 'Artes', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('jessica-maria-orrante-alcaraz', 'Ciencias Iii (énfasis En Química)', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('teresita-de-jesus-ruiz-castaneda', 'Español Iii', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('veronica-pamela-jimenez-gutierrez', 'Formación Cívica Y Ética Ii', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('emilia-elizabeth-sanchez-arellano', 'Historia Iii', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('cecilia-guadalupe-castillo-ortiz', 'Matemáticas Iii', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '3.º de secundaria', 'Grupo A'),
  ('jessica-maria-orrante-alcaraz', 'Ciencias Iii (énfasis En Química)', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('teresita-de-jesus-ruiz-castaneda', 'Español Iii', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética Ii', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('veronica-pamela-jimenez-gutierrez', 'Historia Iii', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('cecilia-guadalupe-castillo-ortiz', 'Matemáticas Iii', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('jesus-fabian-arellano-ornelas', 'Taller De Artes', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '3.º de secundaria', 'Grupo B'),
  ('brenda-elicet-giles-miranda', 'Ciencias Iii (énfasis En Química)', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('jesus-ernesto-ramos-torres', 'Educación Física', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('julio-adrian-cerna-estrada', 'Español Iii', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('cecilia-guadalupe-castillo-ortiz', 'Finanzas Personales', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('eli-andres-lopez-gonzalez', 'Formación Cívica Y Ética Ii', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('veronica-pamela-jimenez-gutierrez', 'Historia Iii', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('elias-marcelo-tejeda-aguirre', 'Matemáticas Iii', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('jesus-fabian-arellano-ornelas', 'Taller De Artes', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('santiago-garate-martinez', 'Tecnología', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('perla-guadalupe-morales-partida', 'Tutoria', 'Secundaria', '3.º de secundaria', 'Grupo C'),
  ('norma-carolina-lizarraga-osuna', 'Advance English 1', 'Secundaria', 'Optativas de secundaria', 'Ingles'),
  ('elizabeth-gaxiola-tirado', 'Advance English 2', 'Secundaria', 'Optativas de secundaria', 'Ingles'),
  ('elizabeth-gaxiola-tirado', 'Advanced 1b', 'Secundaria', 'Optativas de secundaria', 'Ingles'),
  ('beatriz-gutierrez-duran', 'Basic English 1', 'Secundaria', 'Optativas de secundaria', 'Ingles'),
  ('marielisa-osuna-ramirez', 'Basic English 2', 'Secundaria', 'Optativas de secundaria', 'Ingles'),
  ('ana-isabel-laris-cutino', 'Middle English 1', 'Secundaria', 'Optativas de secundaria', 'Ingles'),
  ('sheccid-tirado-cuellar', 'Middle English 2', 'Secundaria', 'Optativas de secundaria', 'Ingles')
) as v(teacher_code, subject, school_level, grade, group_name)
join teachers t on t.code = v.teacher_code
on conflict (teacher_id, cycle_id, subject, grade, group_name) do nothing;
